// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationSystem.Infrastructure.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationSystem.Infrastructure.Migrations
{
    [DbContext(typeof(NotificationSystemContext))]
    [Migration("20240521093138_fourth")]
    partial class fourth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("subscriber_subscriberid_seq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("subscription_subscriptionid_seq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("voucher_voucherid_seq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("voucherproduction_voucherproductionid_seq")
                .IncrementsBy(10);

            modelBuilder.HasSequence("wallettransaction_wallettransactionid")
                .IncrementsBy(10);

            modelBuilder.Entity("NotificationSystem.Domain.Subscription.Subscriber", b =>
                {
                    b.Property<int>("SubscriberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("SubscriberId"), "subscriber_subscriberid_seq");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Package")
                        .HasColumnType("integer");

                    b.Property<decimal>("PackageUnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("SubscriberId");

                    b.ToTable("Subscriber");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Subscription.SubscriberWallet", b =>
                {
                    b.Property<int>("SubscriberId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriberId");

                    b.ToTable("SubscriberWallets");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Subscription.Subscription", b =>
                {
                    b.Property<long>("SubcriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("SubcriptionId"), "subscription_subscriptionid_seq");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("PinNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubscriptionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("integer");

                    b.HasKey("SubcriptionId");

                    b.HasIndex("SubscriberId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Subscription.WalletTransaction", b =>
                {
                    b.Property<long>("WalletTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("WalletTransactionId"), "wallettransaction_wallettransactionid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.HasKey("WalletTransactionId");

                    b.HasIndex("SubscriberId");

                    b.ToTable("WalletTransaction");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Voucher.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("VoucherId"), "voucher_voucherid_seq");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateProduced")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUsed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PinNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UsedByMobileNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VoucherProductionId")
                        .HasColumnType("integer");

                    b.HasKey("VoucherId");

                    b.HasIndex("VoucherProductionId");

                    b.ToTable("Voucher");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Voucher.VoucherProduction", b =>
                {
                    b.Property<int>("VoucherProductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<int>("VoucherProductionId"), "voucherproduction_voucherproductionid_seq");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantityProduced")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("VoucherProductionId");

                    b.ToTable("VoucherProduction");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Subscription.SubscriberWallet", b =>
                {
                    b.HasOne("NotificationSystem.Domain.Subscription.Subscriber", "Subscriber")
                        .WithOne("Wallet")
                        .HasForeignKey("NotificationSystem.Domain.Subscription.SubscriberWallet", "SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Subscription.Subscription", b =>
                {
                    b.HasOne("NotificationSystem.Domain.Subscription.Subscriber", "Subcriber")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcriber");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Subscription.WalletTransaction", b =>
                {
                    b.HasOne("NotificationSystem.Domain.Subscription.SubscriberWallet", "SubscriberWallet")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriberWallet");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Voucher.Voucher", b =>
                {
                    b.HasOne("NotificationSystem.Domain.Voucher.VoucherProduction", "VoucherProduction")
                        .WithMany("Vouchers")
                        .HasForeignKey("VoucherProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoucherProduction");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Subscription.Subscriber", b =>
                {
                    b.Navigation("Subscriptions");

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("NotificationSystem.Domain.Subscription.SubscriberWallet", b =>
                {
                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("NotificationSystem.Domain.Voucher.VoucherProduction", b =>
                {
                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
